import type { Call, RestaurantWithStats } from '@/types/database';

export const mockCalls: Call[] = [
  {
    id: '1',
    restaurant_id: 'r1',
    retell_call_id: 'retell_001',
    start_time: new Date().toISOString(),
    end_time: new Date(Date.now() + 180000).toISOString(),
    duration_seconds: 180,
    transcript:
      'OMRI: Thank you for calling Mario\'s Pizza! How can I help you today?\nCustomer: Hi, I\'d like to place an order for delivery.\nOMRI: Of course! What would you like to order?\nCustomer: I\'ll have a large pepperoni pizza and a Caesar salad.\nOMRI: Great choices! Would you like to add garlic bread for just $3.99? It pairs perfectly with the pizza.\nCustomer: Sure, why not!\nOMRI: Wonderful! So that\'s a large pepperoni pizza at $18.99, a Caesar salad at $8.99, and garlic bread at $3.99. Your total comes to $31.97. Can I confirm your delivery address?',
    call_outcome: 'order_placed',
    order_total: 31.97,
    upsell_total: 3.99,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    restaurant_id: 'r1',
    retell_call_id: 'retell_002',
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: new Date(Date.now() - 3600000 + 45000).toISOString(),
    duration_seconds: 45,
    transcript:
      'OMRI: Thank you for calling Mario\'s Pizza!\nCustomer: Hi, what are your hours today?\nOMRI: We\'re open today from 11 AM to 10 PM. Is there anything else I can help with?\nCustomer: No, that\'s all. Thanks!',
    call_outcome: 'inquiry',
    order_total: 0,
    upsell_total: 0,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '3',
    restaurant_id: 'r1',
    retell_call_id: 'retell_003',
    start_time: new Date(Date.now() - 7200000).toISOString(),
    end_time: new Date(Date.now() - 7200000 + 240000).toISOString(),
    duration_seconds: 240,
    transcript:
      'OMRI: Thank you for calling Mario\'s Pizza!\nCustomer: I want to order two large cheese pizzas, buffalo wings, and a 2-liter Coke.\nOMRI: Perfect! Would you like to upgrade your wings to a double order for just $4 more?\nCustomer: Yeah, do that.\nOMRI: Your total is $52.47. I\'ll confirm that order right away!',
    call_outcome: 'order_placed',
    order_total: 52.47,
    upsell_total: 4.0,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: '4',
    restaurant_id: 'r1',
    retell_call_id: 'retell_004',
    start_time: new Date(Date.now() - 10800000).toISOString(),
    end_time: null,
    duration_seconds: null,
    transcript: null,
    call_outcome: 'missed',
    order_total: 0,
    upsell_total: 0,
    created_at: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: '5',
    restaurant_id: 'r1',
    retell_call_id: 'retell_005',
    start_time: new Date(Date.now() - 14400000).toISOString(),
    end_time: new Date(Date.now() - 14400000 + 300000).toISOString(),
    duration_seconds: 300,
    transcript:
      'OMRI: Thank you for calling Mario\'s Pizza!\nCustomer: Hi, can I get a family combo deal?\nOMRI: Absolutely! Our family combo includes two large pizzas, a salad, and breadsticks for $44.99. Would you like to add drinks for the whole family for just $7.99?\nCustomer: Yes please!\nOMRI: Your total is $52.98. That\'s a great deal!',
    call_outcome: 'order_placed',
    order_total: 52.98,
    upsell_total: 7.99,
    created_at: new Date(Date.now() - 14400000).toISOString(),
  },
];

export const mockHeatmapData: Record<string, Record<number, number>> = {
  Mon: { 11: 3, 12: 8, 13: 5, 17: 12, 18: 15, 19: 10, 20: 6 },
  Tue: { 11: 4, 12: 7, 13: 6, 17: 10, 18: 14, 19: 11, 20: 5 },
  Wed: { 11: 2, 12: 9, 13: 4, 17: 11, 18: 16, 19: 12, 20: 7 },
  Thu: { 11: 5, 12: 10, 13: 7, 17: 13, 18: 18, 19: 14, 20: 8 },
  Fri: { 11: 6, 12: 12, 13: 8, 17: 16, 18: 22, 19: 18, 20: 12 },
  Sat: { 11: 8, 12: 14, 13: 10, 17: 18, 18: 25, 19: 20, 20: 15 },
  Sun: { 11: 7, 12: 11, 13: 9, 17: 14, 18: 19, 19: 15, 20: 10 },
};

export const mockRestaurants: RestaurantWithStats[] = [
  {
    id: 'r1',
    name: "Mario's Pizza",
    address: '123 Main St, Austin, TX',
    phone: '5125551234',
    pos_type: 'square',
    pos_connected: true,
    retell_agent_id: 'agent_001',
    stripe_subscription_id: 'sub_001',
    stripe_customer_id: 'cus_001',
    plan_tier: 'growth',
    created_at: '2024-01-15T00:00:00Z',
    owner_user_id: 'user_001',
    calls_today: 24,
    revenue_today: 842.5,
    last_call_time: new Date(Date.now() - 600000).toISOString(),
    health_status: 'green',
  },
  {
    id: 'r2',
    name: 'Taco Royale',
    address: '456 Elm St, Houston, TX',
    phone: '7135559876',
    pos_type: 'toast',
    pos_connected: true,
    retell_agent_id: 'agent_002',
    stripe_subscription_id: 'sub_002',
    stripe_customer_id: 'cus_002',
    plan_tier: 'starter',
    created_at: '2024-02-01T00:00:00Z',
    owner_user_id: 'user_002',
    calls_today: 18,
    revenue_today: 615.3,
    last_call_time: new Date(Date.now() - 1800000).toISOString(),
    health_status: 'green',
  },
  {
    id: 'r3',
    name: 'Dragon Wok',
    address: '789 Oak Ave, Dallas, TX',
    phone: '2145557654',
    pos_type: 'clover',
    pos_connected: false,
    retell_agent_id: 'agent_003',
    stripe_subscription_id: 'sub_003',
    stripe_customer_id: 'cus_003',
    plan_tier: 'pro',
    created_at: '2024-03-10T00:00:00Z',
    owner_user_id: 'user_003',
    calls_today: 5,
    revenue_today: 120.0,
    last_call_time: new Date(Date.now() - 21600000).toISOString(),
    health_status: 'yellow',
  },
  {
    id: 'r4',
    name: 'Burger Barn',
    address: '321 Pine Rd, San Antonio, TX',
    phone: '2105553456',
    pos_type: 'square',
    pos_connected: true,
    retell_agent_id: null,
    stripe_subscription_id: null,
    stripe_customer_id: null,
    plan_tier: null,
    created_at: '2024-04-01T00:00:00Z',
    owner_user_id: 'user_004',
    calls_today: 0,
    revenue_today: 0,
    last_call_time: null,
    health_status: 'red',
  },
];
