'use client';

import { TrendingUp, ArrowUpRight, DollarSign, Sparkles, Target } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';
import { cn } from '@/lib/utils';

interface RoiSummaryProps {
  monthlyOrderRevenue: number;
  monthlyUpsellRevenue: number;
  totalCalls: number;
}

export function RoiSummary({ monthlyOrderRevenue, monthlyUpsellRevenue, totalCalls }: RoiSummaryProps) {
  const totalRevenue = monthlyOrderRevenue + monthlyUpsellRevenue;
  const avgOrderValue = totalCalls > 0 ? totalRevenue / totalCalls : 0;
  const conversionRate = totalCalls > 0 ? Math.round((monthlyOrderRevenue / totalRevenue) * 100) : 0;

  return (
    <div className="rounded-2xl border border-ringo-teal/20 bg-gradient-to-br from-ringo-teal/[0.08] via-ringo-card to-ringo-card overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-ringo-teal/10">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-ringo-teal/15 p-2.5">
            <TrendingUp className="h-5 w-5 text-ringo-teal" />
          </div>
          <div>
            <h3 className="text-base font-bold text-foreground">Monthly ROI Summary</h3>
            <p className="text-[11px] text-ringo-muted">Revenue generated by your AI agent</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 rounded-full bg-emerald-400/10 px-3 py-1.5">
          <ArrowUpRight className="h-3.5 w-3.5 text-emerald-400" />
          <span className="text-xs font-bold text-emerald-400">+23% vs last month</span>
        </div>
      </div>

      {/* Stats grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 divide-x divide-ringo-border/30">
        <div className="p-5">
          <div className="flex items-center gap-2 mb-2">
            <DollarSign className="h-3.5 w-3.5 text-ringo-muted" />
            <p className="text-[10px] font-bold uppercase tracking-widest text-ringo-muted">Orders</p>
          </div>
          <p className="text-2xl font-bold text-foreground">{formatCurrency(monthlyOrderRevenue)}</p>
          <p className="text-[10px] text-ringo-muted mt-1">captured revenue</p>
        </div>

        <div className="p-5">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="h-3.5 w-3.5 text-ringo-amber" />
            <p className="text-[10px] font-bold uppercase tracking-widest text-ringo-muted">Upsells</p>
          </div>
          <p className="text-2xl font-bold text-ringo-amber">{formatCurrency(monthlyUpsellRevenue)}</p>
          <p className="text-[10px] text-ringo-muted mt-1">extra revenue from AI</p>
        </div>

        <div className="p-5">
          <div className="flex items-center gap-2 mb-2">
            <Target className="h-3.5 w-3.5 text-ringo-purple-light" />
            <p className="text-[10px] font-bold uppercase tracking-widest text-ringo-muted">Avg Order</p>
          </div>
          <p className="text-2xl font-bold text-ringo-purple-light">{formatCurrency(avgOrderValue)}</p>
          <p className="text-[10px] text-ringo-muted mt-1">per call with order</p>
        </div>

        <div className="p-5 bg-gradient-to-br from-ringo-teal/[0.06] to-transparent">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="h-3.5 w-3.5 text-ringo-teal" />
            <p className="text-[10px] font-bold uppercase tracking-widest text-ringo-muted">Total</p>
          </div>
          <p className="text-2xl font-bold text-ringo-teal">{formatCurrency(totalRevenue)}</p>
          <p className="text-[10px] text-ringo-muted mt-1">{totalCalls} calls this month</p>
        </div>
      </div>
    </div>
  );
}
