'use client';

import { TrendingUp, ArrowUpRight, DollarSign, Sparkles, Target } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';
import { cn } from '@/lib/utils';

interface RoiSummaryProps {
  monthlyOrderRevenue: number;
  monthlyUpsellRevenue: number;
  totalCalls: number;
}

export function RoiSummary({ monthlyOrderRevenue, monthlyUpsellRevenue, totalCalls }: RoiSummaryProps) {
  const totalRevenue = monthlyOrderRevenue + monthlyUpsellRevenue;
  const avgOrderValue = totalCalls > 0 ? totalRevenue / totalCalls : 0;

  return (
    <div className="rounded-2xl border border-ringo-teal/20 bg-ringo-card/80 backdrop-blur-sm overflow-hidden ring-1 ring-ringo-teal/5 shadow-sm">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-ringo-teal/10 bg-gradient-to-r from-ringo-teal/[0.06] via-transparent to-transparent">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-ringo-teal/15 p-2.5 shadow-sm shadow-ringo-teal/10">
            <TrendingUp className="h-5 w-5 text-ringo-teal" />
          </div>
          <div>
            <h3 className="text-base font-bold text-foreground">Monthly ROI Summary</h3>
            <p className="text-[11px] text-ringo-muted">Revenue generated by your AI agent</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 rounded-full bg-emerald-50 border border-emerald-200/50 px-3 py-1.5 shadow-sm">
          <ArrowUpRight className="h-3.5 w-3.5 text-emerald-600" />
          <span className="text-xs font-bold text-emerald-600">+23% vs last month</span>
        </div>
      </div>

      {/* Stats grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 divide-x divide-ringo-border/20">
        {[
          { icon: DollarSign, label: 'Orders', value: formatCurrency(monthlyOrderRevenue), sub: 'captured revenue', iconColor: 'text-ringo-muted', valueColor: 'text-foreground' },
          { icon: Sparkles, label: 'Upsells', value: formatCurrency(monthlyUpsellRevenue), sub: 'extra revenue from AI', iconColor: 'text-ringo-amber', valueColor: 'text-ringo-amber' },
          { icon: Target, label: 'Avg Order', value: formatCurrency(avgOrderValue), sub: 'per call with order', iconColor: 'text-ringo-purple-light', valueColor: 'text-ringo-purple-light' },
          { icon: TrendingUp, label: 'Total', value: formatCurrency(totalRevenue), sub: `${totalCalls} calls this month`, iconColor: 'text-ringo-teal', valueColor: 'text-ringo-teal', highlight: true },
        ].map((stat, idx) => (
          <div key={idx} className={cn('p-5 transition-colors', stat.highlight && 'bg-gradient-to-br from-ringo-teal/[0.04] to-transparent')}>
            <div className="flex items-center gap-2 mb-2">
              <stat.icon className={cn('h-3.5 w-3.5', stat.iconColor)} />
              <p className="text-[10px] font-bold uppercase tracking-widest text-ringo-muted">{stat.label}</p>
            </div>
            <p className={cn('text-2xl font-bold', stat.valueColor)}>{stat.value}</p>
            <p className="text-[10px] text-ringo-muted mt-1">{stat.sub}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
