'use client';

import { TrendingUp, ArrowUpRight, DollarSign, Sparkles, Target } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';
import { cn } from '@/lib/utils';

interface RoiSummaryProps {
  monthlyOrderRevenue: number;
  monthlyUpsellRevenue: number;
  totalCalls: number;
}

export function RoiSummary({ monthlyOrderRevenue, monthlyUpsellRevenue, totalCalls }: RoiSummaryProps) {
  const totalRevenue = monthlyOrderRevenue + monthlyUpsellRevenue;
  const avgOrderValue = totalCalls > 0 ? totalRevenue / totalCalls : 0;

  return (
    <div className="rounded-2xl border border-[#C9A84C]/20 bg-ringo-card/80 backdrop-blur-sm overflow-hidden ring-1 ring-[#C9A84C]/5 shadow-sm">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 px-4 sm:px-6 py-4 border-b border-[#C9A84C]/10 bg-gradient-to-r from-[#C9A84C]/[0.06] via-transparent to-transparent">
        <div className="flex items-center gap-2 sm:gap-3 min-w-0">
          <div className="rounded-xl bg-[#C9A84C]/15 p-2.5 shadow-sm shadow-[#C9A84C]/10 flex-shrink-0">
            <TrendingUp className="h-4 sm:h-5 w-4 sm:w-5 text-[#C9A84C]" />
          </div>
          <div className="min-w-0">
            <h3 className="text-sm sm:text-base font-bold text-foreground truncate">This month Ringo made you {formatCurrency(totalRevenue)}</h3>
            <p className="text-[10px] sm:text-[11px] text-ringo-muted">Revenue generated by your AI agent</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 rounded-full bg-[#C9A84C]/10 border border-[#C9A84C]/20 px-2.5 sm:px-3 py-1.5 shadow-sm whitespace-nowrap flex-shrink-0">
          <ArrowUpRight className="h-3 sm:h-3.5 w-3 sm:w-3.5 text-[#C9A84C]" />
          <span className="text-[10px] sm:text-xs font-bold text-[#C9A84C]">+23% vs last month</span>
        </div>
      </div>

      {/* Stats grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 divide-x divide-ringo-border/20">
        {[
          { icon: DollarSign, label: 'Orders', value: formatCurrency(monthlyOrderRevenue), sub: 'captured revenue', iconColor: 'text-ringo-muted', valueColor: 'text-foreground' },
          { icon: Sparkles, label: 'Upsells', value: formatCurrency(monthlyUpsellRevenue), sub: 'extra revenue from AI', iconColor: 'text-ringo-amber', valueColor: 'text-ringo-amber' },
          { icon: Target, label: 'Avg Order', value: formatCurrency(avgOrderValue), sub: 'per call with order', iconColor: 'text-ringo-purple-light', valueColor: 'text-ringo-purple-light' },
          { icon: TrendingUp, label: 'Total', value: formatCurrency(totalRevenue), sub: `${totalCalls} calls this month`, iconColor: 'text-[#C9A84C]', valueColor: 'text-[#C9A84C]', highlight: true },
        ].map((stat, idx) => (
          <div key={idx} className={cn('p-3 sm:p-5 transition-colors', stat.highlight && 'bg-gradient-to-br from-[#C9A84C]/[0.04] to-transparent')}>
            <div className="flex items-center gap-2 mb-2">
              <stat.icon className={cn('h-3 sm:h-3.5 w-3 sm:w-3.5', stat.iconColor)} />
              <p className="text-[9px] sm:text-[10px] font-bold uppercase tracking-widest text-ringo-muted">{stat.label}</p>
            </div>
            <p className={cn('text-lg sm:text-2xl font-bold break-words', stat.valueColor)}>{stat.value}</p>
            <p className="text-[9px] sm:text-[10px] text-ringo-muted mt-1">{stat.sub}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
